---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    vagrant:
      hosts:
        vm1:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: vagrant
          
