proxy_env:
  http_proxy: http://192.168.3.100:4555
  https_proxy: "{{ http_proxy }}"

# http proxy
http_proxy: http://192.168.3.100:4555

# docker variables
docker:
  http_proxy: "{{ http_proxy }}"
  no_proxy: localhost,127.0.0.1,hub.hamdocker.ir,repo.mecan.ir
  log_max_file: "5"
  log_max_size: 100m
  registry_mirror: https://hub.hamdocker.ir