---
- name: install docker
  import_tasks: InstallDocker.yml
  tags: install_docker
  when: ansible_os_family == "Debian"

- name: config docker
  import_tasks: ConfigDocker.yml
  tags: config_docker
  when: ansible_os_family == "Debian"


- name: install compose
  import_tasks: InstallCompose.yml
  tags: install_compose
  when: ansible_os_family == "Debian"

